# Generated by Django 3.1.5 on 2021-03-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
