# Generated by Django 3.1.5 on 2021-03-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='FybookPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('pdf1', models.FileField(upload_to='pdf1/%y')),
            ],
        ),
        migrations.RenameModel(
            old_name='pdf',
            new_name='FypaperPdf',
        ),
    ]
