# Generated by Django 3.1.5 on 2021-03-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210324_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='SybookPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('pdf1', models.FileField(upload_to='pdf1/%y')),
            ],
        ),
        migrations.CreateModel(
            name='SypaperPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdf/%y')),
            ],
        ),
        migrations.CreateModel(
            name='TybookPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('pdf1', models.FileField(upload_to='pdf1/%y')),
            ],
        ),
        migrations.CreateModel(
            name='TypaperPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdf/%y')),
            ],
        ),
    ]
